const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
const {dismissWelcome,useDeveloperEnvironment}=require('./fixtures.cjs');
const BASE=process.env.BASE_URL||'http://127.0.0.1:8081/';const KEY='eco-system:forest-save';
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const contexts=[],errors=[];
 const state=p=>p.evaluate(async()=>structuredClone((await import('./js/main.js')).gameState));
 async function setup({raw,dev=false,url=BASE,reduce=false}={}){
  const context=await browser.newContext({viewport:{width:1280,height:800},hasTouch:true,reducedMotion:reduce?'reduce':'no-preference'});contexts.push(context);
  if(raw)await context.addInitScript(({raw,key})=>{if(!sessionStorage.seeded){localStorage.setItem(key,raw);sessionStorage.seeded='yes'}},{raw,key:KEY});
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.loadedDev=false;page.on('request',r=>{if(r.url().includes('/dev/'))page.loadedDev=true});if(dev)await useDeveloperEnvironment(page);
  await page.goto(url,{waitUntil:'networkidle'});return page;
 }
 const card=(p,id)=>p.locator(`.organism-card[data-species-id="${id}"]`);
 async function place(p,id,x=.44,y=.70){await card(p,id).tap();const box=await p.locator('#placement-surface').boundingBox();await p.touchscreen.tap(box.x+x*box.width,box.y+y*box.height)}
 async function oldSave(p,{factor='water',count=3,cleared=false}={}){return p.evaluate(async({factor,count,cleared})=>{
  const {createGameState}=await import('./js/state/game-state.js');const {createOrganismInstance}=await import('./js/state/organism-instance.js');const {createSaveSnapshot}=await import('./js/services/save-format.js');
  const s=createGameState();s.simulationTime=80;s.environment[factor].value=.15;s.metrics.points=25;s.metrics.bestStability=85;s.forestProgress={cleared,clearedAt:cleared?60:null,stableSeconds:cleared?30:0};
  s.observations=[{relationId:'grass_to_grasshopper',eventId:'old-1',discoveredAt:25}];s.inventory.find(c=>c.speciesId==='frog').acquired=true;
  s.activities.find(a=>a.activityId==='producer_quiz').completed=true;s.activities[0].lastAnswer='grass';s.activities[0].completedAt=30;
  while(s.organisms.length<count)s.organisms.push(createOrganismInstance('rabbit','fixture-'+s.organisms.length,{x:.16+(s.organisms.length%6)*.075,y:.64}));
  return JSON.stringify(createSaveSnapshot(s,{sequence:10,cooldowns:[],questionDone:[],pendingDiscoveries:[]},'2026-10-08T00:00:00.000Z'));
 },{factor,count,cleared})}
 try{
  const p=await setup({reduce:true});assert(await p.locator('#help-dialog').evaluate(d=>d.open));assert.match(await p.locator('#help-purpose').textContent(),/게임 목표.*안정적인 숲/s);
  if(process.env.SCREENSHOT_PATH)await p.screenshot({path:process.env.SCREENSHOT_PATH,fullPage:true});
  await p.locator('#help-start').tap();assert(await p.locator('#help-controls').isVisible());assert.match(await p.locator('#help-controls').textContent(),/카드.*💡.*포인트/s);await p.locator('#help-finish').tap();
  assert.equal((await state(p)).metrics.points,0);await p.locator('#goal-open').tap();assert.equal(await p.locator('#goal-checks li').count(),6);assert.match(await p.locator('[data-goal-group="observations"]').textContent(),/0\/2/);assert.match(await p.locator('[data-goal-group="activities"]').textContent(),/0\/3/);assert.match(await p.locator('#hold-label').textContent(),/30초/);await p.locator('#goal-close').tap();
  assert.match(await p.locator('#next-action').textContent(),/메뚜기.*풀 가까이/);console.log('A/B/C: concise purpose, controls, six live goals, 30-second rule');
  await p.locator('#help-open').tap();await p.locator('#help-skip').tap();assert.equal(await p.locator('#help-dialog').evaluate(d=>d.open),false);
  await place(p,'grasshopper');await p.emulateMedia({reducedMotion:'no-preference'});await p.locator('.event-insight').first().waitFor({timeout:40000});
  await p.locator('.event-insight').first().tap();assert.equal((await state(p)).organisms.length,4);await p.getByRole('button',{name:'살펴보기',exact:true}).click();await p.getByRole('button',{name:'발견 기록하기',exact:true}).click();await p.locator('#event-close').click();
  await p.locator('#goal-open').click();assert.match(await p.locator('[data-goal-group="observations"]').textContent(),/1\/2/);await p.locator('#goal-close').click();assert.match(await p.locator('#next-action').textContent(),/잠긴 개구리/);
  await card(p,'frog').tap();await p.locator('[data-answer="confirm"]').click();await p.locator('#activity-close').click();assert.match(await p.locator('#next-action').textContent(),/개구리 카드를/);await p.emulateMedia({reducedMotion:'reduce'});await place(p,'frog',.42,.70);
  await p.locator('#goal-open').click();assert.equal(await p.locator('[data-goal-group="structure"]').getAttribute('data-achieved'),'true');assert.match(await p.locator('[data-goal-group="activities"]').textContent(),/1\/3/);await p.locator('#goal-close').click();
  await p.locator('#activities-open').click();await p.locator('[data-answer="grass"]').click();await p.locator('#activity-close').click();await p.locator('#goal-open').click();assert.match(await p.locator('[data-goal-group="activities"]').textContent(),/2\/3/);await p.locator('#goal-close').click();console.log('D/E/F: recorded discovery, completed learning and placed unlocked frog update actual goals');
  await p.locator('#environment-open').tap();assert.equal(await p.locator('#environment-fields [data-environment-factor]').count(),4);assert.equal(await p.locator('#environment-dialog select,input').count(),0);assert.equal(await p.locator('#environment-dev-fields').count(),0);await p.locator('#environment-close').tap();assert(!p.loadedDev);
  const q=await setup({url:BASE+'?dev=true&debug=1',reduce:true});await dismissWelcome(q);await q.locator('#environment-open').click();assert.equal(await q.locator('#environment-dialog select,input').count(),0);assert(!q.loadedDev);console.log('G/H: student controls read-only; ordinary URL flags expose no free mutation or developer module');
  const raw=await oldSave(p,{factor:'water'}),saved=await setup({raw});assert.equal(await saved.locator('#help-dialog').evaluate(d=>d.open),false);const restored=await state(saved);assert.equal(restored.schemaVersion,7);assert.equal(restored.environment.water.value,.15);assert.equal(restored.metrics.points,25);assert(restored.inventory.find(c=>c.speciesId==='frog').acquired);assert.equal(restored.observations.length,1);
  await saved.locator('.abiotic-status .event-alert').waitFor({timeout:15000});await saved.locator('.abiotic-status .event-alert').tap();await saved.getByRole('button',{name:'살펴보기',exact:true}).click();await saved.locator('[data-management-action="water-care"]').tap();assert.equal((await state(saved)).environment.water.value,.6);assert.equal((await state(saved)).managementHistory[0].cost,6);assert.equal((await state(saved)).metrics.points,22);await saved.locator('#event-close').click();console.log('I/K: schema 7 bad environment preserved, paid water management and real resolution reward');
  const clearedRaw=await oldSave(p,{factor:'air',cleared:true}),legacy=await setup({raw:clearedRaw,reduce:true});const start=await state(legacy);assert(start.forestProgress.cleared);assert.equal(start.environment.air.value,.15);assert.equal(start.forestProgress.clearedAt,60);
  await legacy.locator('#environment-open').click();await legacy.locator('[data-environment-recovery="air"]').tap();const recovered=await state(legacy);assert.equal(recovered.environment.air.value,.6);assert.equal(recovered.metrics.points,17);assert(recovered.forestProgress.cleared);assert.equal(recovered.managementHistory[0].actionId,'habitat-care');assert.equal(recovered.managementHistory[0].cost,8);await legacy.locator('#environment-close').click();await legacy.locator('#help-open').click();assert(await legacy.locator('#help-dialog').evaluate(d=>d.open));await legacy.keyboard.press('Escape');assert.equal((await state(legacy)).metrics.points,17);console.log('K/L/M: old clear survives; bad air has explicit paid recovery; help reopening preserves progress');
  const sun=await setup({raw:await oldSave(p,{factor:'sunlight'}),reduce:true});assert.equal((await state(sun)).environment.sunlight.value,.15);await sun.locator('#environment-open').click();await sun.locator('[data-environment-recovery="sunlight"]').tap();assert.equal((await state(sun)).environment.sunlight.value,.6);
  const dev=await setup({dev:true,reduce:true});await dismissWelcome(dev);await dev.locator('#environment-open').click();await dev.getByLabel('토양 상태',{exact:true}).selectOption('bad');assert.equal((await state(dev)).environment.soil.value,.15);assert.equal((await state(dev)).metrics.points,0);console.log('J/M: explicit test harness can change factors; sunlight has paid legacy recovery');
  const perfPage=await setup({raw:await oldSave(p,{factor:'water',count:30})});assert.equal((await state(perfPage)).organisms.length,30);await perfPage.locator('#goal-open').click();await perfPage.evaluate(()=>{window.kept=[...document.querySelectorAll('.organism-object')];window.reads=0;const old=Element.prototype.getBoundingClientRect;Element.prototype.getBoundingClientRect=function(){window.reads++;return old.call(this)}});await perfPage.waitForTimeout(2300);
  const perf=await perfPage.evaluate(()=>({stable:window.kept.every((node,i)=>node===document.querySelectorAll('.organism-object')[i]),reads:window.reads}));assert(perf.stable);assert.equal(perf.reads,0);
  for(const [width,height]of [[1280,800],[1138,712],[960,600],[412,915]]){await perfPage.setViewportSize({width,height});await perfPage.waitForTimeout(120);assert.equal(await perfPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(width>=960)assert.equal(await perfPage.evaluate(()=>document.documentElement.scrollHeight>innerHeight),false);const box=await perfPage.locator('#goal-close').boundingBox();assert(box.height>=44)}
  await perfPage.locator('#goal-close').click();await perfPage.setViewportSize({width:1280,height:800});await perfPage.locator('#help-open').click();const helpBox=await perfPage.locator('#help-close').boundingBox();assert(helpBox.width>=44&&helpBox.height>=44);await perfPage.locator('#help-close').click();console.log('O/P: responsive touch and 30-organism stable DOM',JSON.stringify(perf));
  assert.deepEqual(errors,[]);console.log('PASS: guidance A-P (N covered by complete regression suite)');
 }finally{for(const c of contexts)await c.close();await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
